apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kjvyvgyoo-go 
  janus-idp.io/tekton: kjvyvgyoo-go
  backstage.io/kubernetes-id: kjvyvgyoo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kjvyvgyoo-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml